#!/usr/bin/env bash
# This script displays information about subdomains

get_info() {
	local domain=$1
	local sub=$2
	ip=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tail -1)
	rec_type=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tail -1)
	echo "The subdomain $sub is a $rec_type record and points to $ip"
}
if [ $# -eq 2 ]; then
	get_info "$1" "$2"
else
	get_info "$1" 'www'
	get_info "$1" 'lb-01'
	get_info "$1" 'web-01'
	get_info "$1" 'web-02'
fi