#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for file in $(ls -A); do
    if [ ! -d "$file" ] && [[ "$file" == *-* ]]; then
        name_after_dash=${file#*-}
        echo "$name_after_dash"
    fi
done
