#!/usr/bin/env bash
# This bash script to connect to a server without typing a password
Host 100.25.16.172
    HostName 100.25.16.172
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no